### ISSUE TITLE
Number of unique references would be nice...

### ISSUE THREAD

**Issue by Mel-Ri** [saezlab/OmnipathR#1]
Dear developers,

today I was using your amazing OmnipathR tool.

While I was checking the number of references that can be listed, I realized that the number of references is the sum of all mentioned references of all database sources. But I think, it would be nice to get the number of unique references…

Many, many thanks for all your efforts.

Kind regards,
Melanie

**Comment by gabora** [comment]
Thanks @Mel-Ri  for using the issue page. Nice catch. 
the latest commit  8fbe4c22928f758bb2ba2b12d8498a04e63eac07 fixes this problem.
