### ISSUE TITLE
Omnipathdb is down

### ISSUE THREAD

**Issue by karJac** [saezlab/OmnipathR#109]
Hi,

Omnipathdb is down for several days now. Could you please look into it?
https://omnipathdb.org/
![image](https://github.com/user-attachments/assets/c3a312ca-74a9-46e5-8ed5-368e9de31f64)

Thank you for constantly maintaining this package and DB!

**Comment by deeenes** [comment]
Thanks for reporting! It was down some time between Mon-Tue this week. Since then, apparently the main page fails to render, but the web service itself is up and running.
