### ISSUE TITLE
Interaction with BioModelAnalyzer

### ISSUE THREAD

**Issue by hallba** [saezlab/OmnipathR#11]
BioModelAnalyzer is a graphical tool for network building and model analysis. The development version (currently hosted on http://bmanewdesign.azurewebsites.net/tool.html) can paste valid json files as models directly onto the canvas. 

Adding an option to print paths to BMA json would be useful

**Comment by alberto-valdeolivas** [comment]
Hello Ben,

Many thanks for your comment and for the pull request you created. This is indeed a very interesting point and it could be an appealing functionality to add to the package. However, I wonder if the option to export paths to JSON format would be more suitable in a more general package like _igraph_. In our package, we mainly retrieve the information from the Omnipath webservice and we transform it to data frames and _igraph_ objects. Indeed, your functions deal with objects from the _igraph_ package. It seems that a discussion about Import/Export graph as JSON files already took place for the _igraph_ package:

https://github.com/igraph/igraph/issues/957

On the other hand, we are currently submitting our package to Bioconductor so we cannot include the new functionalities you proposed right now. I will merge your pull request to a new branch. 

I will also discuss with my colleagues about including your functions to our package and come back to you.

Best regards,
Alberto.

**Comment by hallba** [comment]
Hi Alberto

Thanks for your feedback. iGraph is inappropriately general for this type of export- here we need to build models that take information from OmniPath directly into account (here the PMID and associated upstream elements). 

I've developed a more powerful example of model export from omnipath (leaving out R entirely), available here https://github.com/hallba/Z3Tutorials (see minimumGenes.fsx). This takes a set of genes, calculates the minimum set required to link them, makes a layout and exports the json to the clipboard.

Ultimately it may be appropriate to link BMA to OmniPath, but in the meantime these scripts make OmniPath more useful for network modelling.

best wishes

Ben
