### ISSUE TITLE
generate_homologs : No method for filter for class "list"

### ISSUE THREAD

**Issue by Dalhte** [saezlab/OmnipathR#111]
Hello there
I have a problem with the generate_homologs function : 
> ortholog_resource <- generate_homologs(op_resource = op_resource,
+                                        target_organism = 10116) # Rat
[2024-10-19 17:20:23] [SUCCESS] [OmnipathR] NCBI HomoloGene (rescued.omnipathdb.org): downloaded 2 records
Erreur dans UseMethod("filter") : 
  pas de méthode pour 'filter' applicable pour un objet de classe "list"

Suspecting a incompatibility problem, I tried to modify the function by forcing  dplyr::filtr but to no end
Best
David

**Comment by deeenes** [comment]
Hello, This is a networking issue, the "downloaded 2 records" suggests accessing NCBI Homologene failed. The corrupted file in the cache blocks the attempt for a new download, hence it has to be removed. One option is to remove it by hand, based on the log:

```
library(OmnipathR)

omnipath_set_console_loglevel('trace')
h <- homologene_raw()

# remove corrupted cache content, e.g.
# rm ~/.cache/OmnipathR/17adac3f05a1830fa9196b2637fd2121a4742cbb-1.rds

omnipath_cache_clean_db()

# attempt new download

h <- homologene_raw()
```

Or wipe the cache completely:

```
library(OmnipathR)

omnipath_get_cachedir()
# rm -rf ~/.cache/OmnipathR/*
```

If it keeps failing, please share the log (find it by `omnipath_logfile()`).
