### ISSUE TITLE
Signor database identifiers are wrong.

### ISSUE THREAD

**Issue by juliangkr** [saezlab/OmnipathR#16]
Hey, thanks a lot for providing this tool, it is a great!

I think there is a minor typo in your guides. You describe that the user can download Signor interaction data using the 'Signor' identifier, however I think uppercase letters are required: 'SIGNOR'.

``` {r}
interactions <- import_Omnipath_Interactions(filter_databases=c("SignaLink3","PhosphoSite", 
  "SIGNOR"))
```

instead of:

``` {r}
interactions <- import_Omnipath_Interactions(filter_databases=c("SignaLink3","PhosphoSite", 
  "Signor"))
```

**Comment by deeenes** [comment]
Hi, thanks for reporting, fixed in eb10957, will be in master soon
