### ISSUE TITLE
R script for viper with OmnipathR regulons

### ISSUE THREAD

**Issue by StevenVanLaere** [saezlab/OmnipathR#17]
Dear Julio,

Do you have a script on how to combine regulon data from OmniPathR with the BioConductor package “viper”?

Much appreciated. Thanks.

Steven Van Laere

**Comment by alberto-valdeolivas** [comment]
Dear Steven,

- We frequently combine Dorothea regulons with Viper using the Dorothea R package. You can check the website here: 

[https://saezlab.github.io/dorothea](https://saezlab.github.io/dorothea)

In the articles section, you can find two notebooks explaining how to run Dorothea regulons coupled with Viper on bulk and single cell data to obtain TF activity. 

- Dorothea regulons are also available via OmnipathR (excepting the interactions with the lowest condifence level). You can check OmnipathR website: 

[https://saezlab.github.io/OmnipathR/](https://saezlab.github.io/OmnipathR/ )

and in particular the vignette in the articles section and the function to import the regulons:

https://saezlab.github.io/OmnipathR/reference/import_dorothea_interactions.html

I hope this helps. Please, do not hesitate to come back with furter questions. 

Best,
Alberto.

**Comment by StevenVanLaere** [comment]
Dear Alberto,

Thanks for your answer. 

I was going through the vignette of the viper package, and I got particularly interested in the synergy and shadow analysis that comes with the msViper function. I can see that the run_viper function from the dorothea package uses regulons in table format, and I wonder if this is possible for the msViper function too. At the moment I can only see that the latter runs with a proper regulon object. Is there a way to generate the regulon objects?

Thanks.

Steven

**Comment by alberto-valdeolivas** [comment]
Dear Steven,

The Dorothea package has an internal function to convert the TF-target interactions into regulon objects: 

https://github.com/saezlab/dorothea/blob/master/R/helpers.R

Let me know if this is what you need. 

Best regards,
Alberto.

**Comment by StevenVanLaere** [comment]
Dear Alberto,

Thanks! I will give it a shot. The resulting regulons also work with msViper?

Thanks a lot.

Steven

**Comment by alberto-valdeolivas** [comment]
Yeah. In principle they should work, the regulon object should be the same for both functions: viper and msViper
