### ISSUE TITLE
getURL() failed

### ISSUE THREAD

**Issue by sigven** [saezlab/OmnipathR#19]
Hi,

Thanks for a great resource! I am using the `import_OmniPath_annotations` method for human genes, but for some selections of genes, the URL is not responding, and I recieve and error, e.g.:

`cannot open URL 'https://omnipathdb.org/annotations?&proteins=YTHDF3,YTHDF2,YTHDF1,YTHDC2,YTHDC1,YRDC,YPEL5,YPEL4,YPEL3,YPEL2,YPEL1,YOD1,YME1L1,YLPM1,YKT6,YJU2,YJEFN3,YIPF7,YIPF6,YIPF5,YIPF4,YIPF3,YIPF2,YIPF1,YIF1B,YIF1A,YES1,YEATS4,YEATS2,YDJC,YBX3,YBX2,YBX1,YBEY,YARS2,YARS1,YAP1,YAF2,YAE1,XYLT2,XYLT1,XXYLT1,XRRA1,XRN2,XRN1,XRCC6,XRCC5,XRCC4,XRCC3,XRCC2`

Not sure why this fails, got any idea?

On beforehand, thanks!

regards,
Sigve

**Comment by deeenes** [comment]
Hi Sigve,

Thanks for your report. We know about this issue, it is a server side error, it happens if for some resource the license is unknown. We will fix it still today, I will close this issue once fixed.

Best wishes,

Denes

**Comment by asumann** [comment]
Hi @deeenes,

I am getting a similar error with this code in the vignette. Hope you can help me figure that out.
```
HPA_small <- import_omnipath_annotations(
  proteins = c('TP53', 'LMNA'),
  resources = c('HPA_tissue'),
  wide = TRUE
)

Error in (function (URL, FUN, ..., N.TRIES = 1L)  : 
  omnipath_download() failed:
  URL: https://omnipathdb.org/annotations?resources=HPA_tissue&proteins=TP53,LMNA&license=academic
  error: cannot open the connection to 'https://omnipathdb.org/annotations?resources=HPA_tissue&proteins=TP53,LMNA&license=academic'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://omnipathdb.org/annotations?resources=HPA_tissue&proteins=TP53,LMNA&license=academic': HTTP status was '500 Internal Server Error'
```
All the best,
Asuman

**Comment by deeenes** [comment]
Hi Asuman,

Looks like it was a temporary disruption, probably the server was overloaded.
The same query was successful for me. Let me know if you are still experiencing this issue.

Best,

Denes

**Comment by asumann** [comment]
Works perfectly now, many thanks!
