### ISSUE TITLE
Plyr dependency

### ISSUE THREAD

**Issue by hallba** [saezlab/OmnipathR#2]
Running commands from the readme, the first command after install fails with an unloaded dependency

> ptms = import_Omnipath_PTMS(filter_databases=c("PhosphoSite", "Signor"))
[1] "Downloaded 25143 interactions"
Error in loadNamespace(name) : there is no package called ‘plyr’

Installing and loading the library allows the command to run

**Comment by gabora** [comment]
thanks for the report! we will shortly get rid of `plyr` dependency and move with `dplyer` only.

**Comment by gabora** [comment]
fixed.
