### ISSUE TITLE
import_Omnipath_PTMS() not working

### ISSUE THREAD

**Issue by humzalikhan** [saezlab/OmnipathR#21]
Seems like something on the server side or formatting of data? So odd, I was using it 2 days ago just fine... 

Error below: 
Downloaded 0 PTMs
Error in strsplit(interactions$sources, ";") : non-character argument
In addition: Warning message:
In FUN(URL, ...) :
  incomplete final line found by readTableHeader on 'http://omnipathdb.org/ptms/?fields=sources&fields=references&fields=curation_effort&genesymbols=1'

**Comment by deeenes** [comment]
Hi,

For me it works with the recent version (`1.3.5`):

```
e <- import_omnipath_enzsub()
# Downloaded 39201 enzyme-substrate relationships.

# or the old name, which works the same apart from a deprecation warning:
e <- import_Omnipath_PTMS()
# Downloaded 39201 enzyme-substrate relationships.
# Warning message:
# 'import_Omnipath_PTMS' is deprecated.
# Use 'import_omnipath_enzsub' instead.
```

Based on the `incomplete final line found by readTableHeader` it looks like a failed network transfer? Please let us know if this error persists.

Best,

Denes

**Comment by deeenes** [comment]
Closing because no confirmation if the issue persists. Please feel free to re-open.
