### ISSUE TITLE
Is import_dorothea_interactions downgraded?

### ISSUE THREAD

**Issue by asumann** [saezlab/OmnipathR#23]
Hi,

I am following "Interaction sources comparison: NicheNet VS Omnipath" analysis. In the Omnipath version used in that analysis, there are some differences in certain function names. It is fine for most functions, I just had to capitalize initials. But  ```import_dorothea_interactions``` is not available at all. Is everything alright with the version I am using? Or, is there a specific reason for downgrading the function, if it is the case?

Many thanks for this amazing package!

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] OmnipathR_1.2.1     readr_1.4.0         VennDiagram_1.6.20 
[4] futile.logger_1.4.3 gprofiler2_0.2.0    tidyr_1.1.2        
[7] igraph_1.2.6       
```

**Comment by deeenes** [comment]
Hi @asumann ,

The latest version of OmnipathR in Bioconductor is 2.0.0, I would suggest to update your installation: http://bioconductor.org/packages/release/bioc/html/OmnipathR.html

It's even better to install from github:
```
require(devtools)
install_github('saezlab/OmnipathR')
```

At some point we changed some method names to make the naming more consistent (but left most the old names in place with a deprecation warning). In the current version `import_dorothea_interactions` retrieves the DoRothEA TF-target interactions, only the A and B confidence levels by default, see the `dorothea_levels` parameter. The `import_tf_target_interactions` function retrieves similar data from other TF-target resources (ORegAnno, PAZAR, etc). And the `import_transcriptional_interactions` includes both DoRothEA and the other resources.

Best,

Denes

**Comment by asumann** [comment]
@deeenes Thank you for the details and suggestions. Updating the installation worked!
