### ISSUE TITLE
Timeline to merge BMA branch

### ISSUE THREAD

**Issue by hallba** [saezlab/OmnipathR#24]
Is there a timeline to merge the BMA... branch? The code was independent within the code base, but the branch has fallen substantially behind master.

**Comment by deeenes** [comment]
Hi @hallba,

Currently I am the maintainer, and I didn't know about this branch.
Thanks very much for your contribution. Now I merged it, but it would be very helpful if you could come up with another pull request, with a little docstring for each function (what it does, what are the parameters), and also mark the functions which should be publicly exported (vs. the others which remain internal).

Best,

Denes

**Comment by hallba** [comment]
Added the notes and made the pull request!

**Comment by deeenes** [comment]
Great, many thanks! Now it's merged to master.
