### ISSUE TITLE
question in extracting different cofactor types

### ISSUE THREAD

**Issue by jv-20** [saezlab/OmnipathR#30]
Hi @deeenes 

I followed your suggestion from the previous post #28  to get the cofactor information- which is great.  I have couple of questions. 

```
cofactor_ligand <- import_intercell_network(
    transmitter_param = list(parent = 'ligand_regulator', causality = NA),
    receiver_param = list(parent = 'ligand', causality = NA)
)
cofactor_receptor <- import_intercell_network(
    transmitter_param = list(parent = 'receptor_regulator', causality = NA),
    receiver_param = list(parent = 'receptor', causality = NA)
)
```

1. I tried to see the different types of cofactors in these two categories. I was wondering if you could comment on the definition of third type of cofactors - ligand_regulator and receptor regulator?

![Q1_COFA](https://user-images.githubusercontent.com/68548237/117988813-a81b5680-b333-11eb-84ec-b42b420c68f9.PNG)

2. Another question is from the co-factor table, what is the difference between columns "is_stimulation" and "consensus_stimulation". Likewise "is_inhibition" vs "consensus_inhibition"?

Thank you,
Janaki

**Comment by deeenes** [comment]
Hi Janaki,

1: The "regulator" only means that we don't know whether it has a negative or positive effect.

2: The "consensus" columns intended to address the ambiguities, when one interaction is described as both stimulation and inhibition, or both directed in one way and the other way around. It is a majority vote between resources and references. However, often both versions are supported by the same number of provenances, and in those cases the ambiguity remains. The consensus columns are not a very successful attempt, I think these are able to remove only a few hundreds of maybe couple of thousands of ambiguous interactions.

Best,

Denes

**Comment by jv-20** [comment]
Thank you Denes, that's helpful.  My question is answered. 

Kind regards,
Janaki
