### ISSUE TITLE
Using NicheNet with OmnipathR in windows

### ISSUE THREAD

**Issue by jv-20** [saezlab/OmnipathR#32]
Hello there,

I would like to use NicheNet with OmnipathR. I was following this tutorial [http://www.bioconductor.org/packages/release/bioc/vignettes/OmnipathR/inst/doc/nichenet.html]

and received the following error message in 

```
Error in parallelStart(mode = MODE_MULTICORE, cpus = cpus, level = level,  : 
  Multicore mode not supported on windows!

```
when running this code

```
nichenet_results <- nichenet_main(
    expressed_genes_transmitter = expressed_genes_transmitter,
    expressed_genes_receiver = expressed_genes_receiver,
    genes_of_interest = genes_of_interest,
    background_genes = background_genes,
    signaling_network = list(
        cpdb = NULL,
        evex = list(min_confidence = 1.0)
    ),
    gr_network = list(only_omnipath = TRUE),
    n_top_ligands = 20,
    mlrmbo_optimization_param = list(ncores = 4)
)
```

Could you please advise?

Thanks,
Janaki

**Comment by deeenes** [comment]
Hi Janaki,

First we should find out where this issue happened exactly. A `traceback()` output (right after the error happens) and an OmnipathR log (find the logfile by `omnipath_logfile()`) could help with this. It should originate from the call of a `nichenetr` function, and a subcall probably to the `parallelMap` package, probably via the `mlr` package.

As these packages are not developed by me, likely you need to ask the `nichenetr` developers, and maybe they too will send you to the `mlr` developers.

Best,

Denes

**Comment by adesalegn** [comment]
Hi Deeenes, 

I just encounter the same problem and errors are below.
 
[Computing y column(s) for design. Not provided.
Mapping in parallel: mode = multicore; level = mlrMBO.feval; cpus = 12; elements = 160.
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 160 slave jobs, displaying at most 10 of them:

00001: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00002: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00003: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00004: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00005: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00006: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00007: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00008: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00009: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00010: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value](url)


## Tracing back where it comes 
traceback()
12: stop(obj)
11: stopf("Errors occurred in %i slave jobs, displaying at most 10 of them:\n\n%s\n%s", 
        n, collapse(msgs, sep = "\n"), extra.msg)
10: stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character))
9: checkResultsAndStopWithErrorsMessages(res)
8: parallelMap(wrapFun, xs.trafo, level = "mlrMBO.feval", impute.error = if (is.null(imputeY)) NULL else identity)
7: evalTargetFun.OptState(opt.state, xs, extras)
6: evalMBODesign.OptState(opt.state)
5: mboTemplate.OptProblem(opt.problem)
4: mboTemplate(opt.problem)
3: mbo(obj_fun, design = design, learner = surr.rf, control = ctrl, 
       show.info = TRUE, more.args = additional_arguments)
2: FUN(X[[i]], ...)
1: lapply(1, mlrmbo_optimization, obj_fun = obj_fun_multi_topology_correction, 
       niter = 8, ncores = 12, nstart = 160, additional_arguments = additional_arguments_topology_correction)
