### ISSUE TITLE
Reproducing the cytoscape visualization

### ISSUE THREAD

**Issue by jv-20** [saezlab/OmnipathR#34]
Hi @deeenes 

Thank you again for the resource and walkthrough examples of two datasets in the paper.

I would like to reproduce a similar cytoscape visualization you have in Figure 5A. It looks really beautiful. I was wondering if you could advise about the cytoscape  layout name you used to generate this figure. 

![Fig5a_Omnipathr_page](https://user-images.githubusercontent.com/68548237/134217501-96d6db78-7c7b-4536-8368-af4115d0d5da.PNG)

Thank you,
Janaki

**Comment by deeenes** [comment]
Hi Janaki,

This figure is the work of Alberto, I am tagging him here and see if he can answer: @alberto-valdeolivas 

Best,

Denes

**Comment by alberto-valdeolivas** [comment]
Hello @jv-20 and @deeenes! 

I used the **yFiles hierarchic layout** from the  **yFiles Layout Algorithms cytsocape** app. Then, we still played a bit more with the position of some nodes in a more "manual" way using https://graphviz.org/.

Hope it helps! 

Best,
Alberto.

**Comment by jv-20** [comment]
Thanks you @alberto-valdeolivas , thank you @deeenes . That's helpful. 

Much appreciated your answers. Thanks again!

Kind regards,
Janaki

**Comment by jv-20** [comment]
Hi @deeenes Hi @alberto-valdeolivas 

Another quick question for Figure 5A, It would be great if ye could advise on this.

- did you use the nichenetR's ligand_target_signaling_path function to determine the signaling path between ligand and target `https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md`

- also if you pruned the signalling pathway output from NicheNet when using graphviz and if so how you made those decisions?

Thank you,
Janaki

**Comment by alberto-valdeolivas** [comment]
Hello, 

The notebooks to reproduce the results of the OmniPath-based NicheNet case study are in this other [repository](https://github.com/saezlab/NicheNet_Omnipath).

In particular, to generate the figure 5A, we did not use the nichenet's function. We used our own approach as described here: 

https://github.com/saezlab/NicheNet_Omnipath/blob/master/07_LigandTargetPaths.md

Best,
Alberto.

**Comment by jv-20** [comment]
That's great! Many thanks @alberto-valdeolivas

**Comment by jv-20** [comment]
Hi @alberto-valdeolivas 

One other question. Could you please advise where I could get these files? I can't seem to locate folder `OmniNetworks_NNformat ` or these files within ` Results ` folder. 

```
lr_network_Omnipath = readRDS("OmniNetworks_NNformat/lr_Network_Omnipath.rds")
sig_network_Omnipath = readRDS("OmniNetworks_NNformat/sig_Network_Omnipath.rds")
gr_network_Omnipath = readRDS("OmniNetworks_NNformat/gr_Network_Omnipath.rds")

ligand_target_matrix = readRDS("Results/ligand_target_matrixWithweights.rds")
weighted_networks <- readRDS("Results/weighted_networksWithSourceWeights.rds")
ligand_tf_matrix <- readRDS("Results/ligand_target_matrixWithweights.rds")

```

Is `ligand_target_matrix `and `ligand_tf_matrix`  the same?

I am using mouse data.  By using  `convert_human_to_mouse_symbols` function I should be able to use the above mentioned files for my analysis isn't it? 

Thanks,
Janaki

**Comment by alberto-valdeolivas** [comment]
Hello, 

Those files are generated in previous scripts that are also available in the repo. The function `convert_human_to_mouse_symbols` is from the `nichenetr ` package, so I do not know the details but I guess it just uses homology translation between human and mouse genes. The networks that we are using are human specific, so you really need to interpret the results with care if you use them for mice. Ideally, you should generate your own mouse specific networks and train with them the nichenet model to generate your own `ligand_target_matrix ` for mouse. 

Best,
Alberto.

**Comment by jv-20** [comment]
Okay thanks @alberto-valdeolivas
