### ISSUE TITLE
TF-target interactions - cancer

### ISSUE THREAD

**Issue by sigven** [saezlab/OmnipathR#35]
Hi,

First of all, thanks for a fantastic and very comprehensive resource!

I was looking at the regulatory interactions (i.e. `OmnipathR::import_transcriptional_interactions`), and had some questions regarding the output.

1) I see that you have established a [cancer-dedicated TF-target interaction dataset](https://saezlab.github.io/dorothea/reference/dorothea_hs_pancancer.html) as part of the [DoRothEA package](https://saezlab.github.io/dorothea/index.html), which from what I can see was based on network inference with ARACNE using TCGA as the (pan-cancer) expression dataset. In the `source` column output from `improt_transcriptional_interactions()` there is however only the `ARACNe-GTEx_DoRothEA`, and no source with ARACNE networks inferred with TCGA, is that correct? Are all the interactions in the *dorothea_hs_pancancer* also found in the interactions returned by `import_transcriptional_interactions()`?

2) The columns `consensus_inhibition` and `consensus_stimulation` found in the data frame returned by `import_transcriptional_interactions()`, what do they mean? Does it mean that there are conflicting evidence for these interactions (i.e. if they are 1/TRUE)?

Regards,
Sigve

**Comment by deeenes** [comment]
Hi Sigve,

In the OmniPath web service we distribute only the generic DoRothEA dataset, not the one generated based on TCGA. As it is based on a different collection of expression signatures, I think the resulted regulons should be different. If you want to use the cancer specific dataset, you can do it by the DoRothEA package.

We added the consensus columns to make it easier to deal with ambiguous directions or effect signs. The values in these columns show a majority vote across resources and references on the direction and signs. However, in case of a tie, these columns still show the ambiguous values, i.e. if A->B and B->A both supported by the same number of evidences, the `consensus_direction` will be true for both. Overall we could remove only a few hundreds of ambiguous interactions this way, so I wouldn't call the attempt very successful or useful.

Best,

Denes

**Comment by sigven** [comment]
Great, thanks for the explanation! I also noticed the [aracne.networks](https://bioconductor.org/packages/release/data/experiment/vignettes/aracne.networks/inst/doc/aracne.networks.pdf) package, which appear somewhat as tumor-type specific versions of the pancancer dataset you provide in the DoRothEA package(?). 

Finally, in your DoRothEA-generated interaction set, is it so that a *mor (mode-of-regulation)*  value of **-1** indicate repression/inhibition, and a value of **1** indicate stimulation?

best,
Sigve

**Comment by deeenes** [comment]
That's correct, *mor* -1 is repression, 1 is stimulation.

Taking just a quick glance, you are right about aracne.networks, although I don't know the details. Maybe @christianholland can confirm

**Comment by sigven** [comment]
One more thing: I see that the set of interactions returned by `OmnipathR::import_transcriptional_interactions()` is orders of magnitude greater than the set found in `dorothea::dorothea_hs`. Can you give some insight as to what the differences are due to?

**Comment by sigven** [comment]
Still trying to figure out the difference between what's available in `OmnipathR`, and what is available in the `dorothea` package. E.g.:

`dorothea_interactions1 <- OmnipathR::import_dorothea_interactions(dorothea_levels = c("A","B","C","D"))`
`dorothea_interactions2 <- dorothea::dorothea_hs %>% dplyr::filter(confidence != "E")`
`dorothea_interactions3 <- dorothea::entire_database %>% dplyr::filter(confidence != "E") ## only human interactions?`

`nrow(dorothea_interactions1)`
[1] 279590
`nrow(dorothea_interactions2)`
[1] 29086
`nrow(dorothea_interactions3)`
[1] 309009
