### ISSUE TITLE
Putative issue with estimating kinase activity based on information from Omnipath db using cancer phosphoproteomics measurements

### ISSUE THREAD

**Issue by Jasonmbg** [saezlab/OmnipathR#37]
Dear OmnipathR community,

initially congrats for this great and comprehensive resource !! My major question is based on the utilization of Omnipath db, within the analysis of a cancer phosphoproteomics dataset, in the context of estimating kinase activities based on various comparisons;

In detail, 

following the according vignette https://github.com/saezlab/kinase_tf_mini_tuto, I performed pairwise comparisons with limma to identify differentially phosphorylated peptides for 14 different conditions/timepoints; afterwards, using the vignette with Omnipath, I computed kinase activity analysis, in which I have attached two representative plots;

[KinaseActivity.Sel.Plots.zip](https://github.com/saezlab/OmnipathR/files/7607683/KinaseActivity.Sel.Plots.zip)

As you can see, in the top perturbed targets, there are genes like IGF1 and ILB; however, these are not kinases/phosphatases; Thus, I incorrectly interpret the results, or indeed the analysis should not be mentioned kinase activity analysis, as on the results it includes targets that are not direct kinases/phosphatases?

```
omnipath_ptm <- get_signed_ptms()
omnipath_ptm <- omnipath_ptm[omnipath_ptm$modification %in% c("dephosphorylation","phosphorylation"),]
sel.omnipath <- omnipath_ptm %>% filter(enzyme_genesymbol%in%c("IGF1","IL1B"))
```

I just had a brief navigation into the Omnipath db, and I have attached a small snapshot as a tsv file, with the information regarding the signaling interactions keeping only IGF1 and IL1B; as you can see, both IGF1 and IL1B are mentioned in the column enzyme_genesymbol, and you see that there are various entries in the substrate_genesymbol, based on the enzyme-substrate relationship, along with the status (i.e. phosphorylation) and other information; that is why these are also appeared in the activity analysis?

[Omnipath.DB.Check.Phospho.IGF1.IL1B.tsv.zip](https://github.com/saezlab/OmnipathR/files/7607698/Omnipath.DB.Check.Phospho.IGF1.IL1B.tsv.zip)

To further expand this, one “plausible explanation” , as also found from the this publication: https://skeletalmusclejournal.biomedcentral.com/articles/10.1186/2044-5040-1-4  

**_“A simplified scheme of the IGF1-Akt pathway is shown in Figure 1. Binding of IGF1 to its receptor leads to activation of its intrinsic tyrosine kinase and autophosphorylation, thus generating docking sites for insulin receptor substrate (IRS), which is also phosphorylated by the IGF1 receptor.”_**

Indeed, in the tsv file I have attached, there is a relationship of enzyme->substrate with IGF1 to AKT1, with the modification phosphorylation; thus, if the total translation of the activity refers also not only to direct kinases, but also other enzymes/growth factors that indirectly promote activation/de-activation of signaling cascades like this, then the total description of the analysis should be changed to something more general? Or another step would be to completely refine the db from R, keeping only known kinases/phosphatases in the enzyme_genesymbol?

For example, one quick and robust solution, would be to download a curated list of kinases/phosphatases? And as a second step, directly filter the omnipath network like this:

```
omnipath_ptm <- get_signed_ptms()
omnipath_ptm <- omnipath_ptm[omnipath_ptm$modification %in% c("dephosphorylation","phosphorylation"),]
sel.omnipath <- omnipath_ptm %>% filter(enzyme_genesymbol%in%kinase/phosphatase_vector) ?
```

Thank you in advance and looking forward for your feedback :)

```
sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] limma_3.50.0    PhosR_1.4.0     readxl_1.3.1    forcats_0.5.1   stringr_1.4.0   dplyr_1.0.7    
 [7] purrr_0.3.4     readr_2.1.0     tidyr_1.1.4     tibble_3.1.6    ggplot2_3.3.5   tidyverse_1.3.1
[13] decoupleR_2.0.0 OmnipathR_3.2.0

```

**Comment by deeenes** [comment]
Dear @Jasonmbg,

Thanks for reporting these likely erroneous database records.
As all databases, the resources constituting OmniPath contain wrong records, some of them more, others less. Here we see all these records are from only one resource called ProtMapper. ProtMapper uses literature mining algorithms (REACH, Sparser), which are known to produce a number of false positives in their output. Seeing the high number of false positives, I might consider removing ProtMapper from OmniPath in the future, or separating from other resources, actually it's authors also recommended this. For you I recommend removing the only ProtMapper interactions from your data frame:

```{r}
omnipath_ptm %>% dplyr::filter(grepl('ProtMapper', sources) & n_resources == 1)
```

Best,

Denes

**Comment by Jasonmbg** [comment]
Dear @deeenes,

good morning and thank you very much for confirming this discrepancy; thus, for directly estimating kinase activity analysis, the above code chunk would suffice for removing these false positives, correct?

Best regards,

Efstathios

**Comment by deeenes** [comment]
Yes. And if you want to further reduce false positives, you can remove all the rest which have no literature references (and not from PhosphoSite -- we might miss some of the PS references). ProtMapper is tricky, bc it has references, but it's false positive rate is high.
