### ISSUE TITLE
DoRothEA files 

### ISSUE THREAD

**Issue by adesalegn** [saezlab/OmnipathR#38]
Hi Omnipath team,

Thank you so much for crating this tool. 
While go thorough the documentation at [](https://workflows.omnipathdb.org/nichenet1.html,)  I could not able to download the file DoRothEA in the link below. 
[](https://github.com/saezlab/DoRothEA/tree/master/data/TFregulons/consensus/table)

Thank you!

**Comment by deeenes** [comment]
Hi,

Apologies for missing to answer this issue until now. I don't see which link are you talking about. However, to retrieve DoRothEA you can use [this function](https://saezlab.github.io/OmnipathR/reference/import_dorothea_interactions.html), and for further transcriptional regulatory interactions [this function](https://saezlab.github.io/OmnipathR/reference/import_tf_target_interactions.html), both together by [this one](https://saezlab.github.io/OmnipathR/reference/import_transcriptional_interactions.html). For example:

```
library(OmnipathR)
dorothea <- import_dorothea_interactions(dorothea_levels = c('A', 'B', 'C'))
``` 

I hope this helps, please let me know if you have further questions.

Best,

Denes
