### ISSUE TITLE
Optimizing  the interactions in the network produced an error 

### ISSUE THREAD

**Issue by adesalegn** [saezlab/OmnipathR#39]
Hi Deeenes,

I was using your package for my study and all was cool but  the code below was giving me an error.
If you have some time I would really appreciate it your answer  

```
optimization_results = lapply(1,mlrmbo_optimization, 
                              obj_fun = obj_fun_multi_topology_correction, 
         niter = 8, ncores = 6, nstart = 160, 
         additional_arguments = additional_arguments_topology_correction)

```
the error was here 

```
Computing y column(s) for design. Not provided.
Mapping in parallel: mode = multicore; level = mlrMBO.feval; cpus = 12; elements = 160.
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) :
Errors occurred in 160 slave jobs, displaying at most 10 of them:

00001: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00002: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00003: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00004: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00005: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00006: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00007: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00008: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00009: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value

00010: Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G), :
At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value](url)
```
Tracing back where it comes
```
traceback()
12: stop(obj)
11: stopf("Errors occurred in %i slave jobs, displaying at most 10 of them:\n\n%s\n%s",
n, collapse(msgs, sep = "\n"), extra.msg)
10: stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character))
9: checkResultsAndStopWithErrorsMessages(res)
8: parallelMap(wrapFun, xs.trafo, level = "mlrMBO.feval", impute.error = if (is.null(imputeY)) NULL else identity)
7: evalTargetFun.OptState(opt.state, xs, extras)
6: evalMBODesign.OptState(opt.state)
5: mboTemplate.OptProblem(opt.problem)
4: mboTemplate(opt.problem)
3: mbo(obj_fun, design = design, learner = surr.rf, control = ctrl,
show.info = TRUE, more.args = additional_arguments)
2: FUN(X[[i]], ...)
1: lapply(1, mlrmbo_optimization, obj_fun = obj_fun_multi_topology_correction,

```

Thank you!

**Comment by deeenes** [comment]
Hi @adesalegn,

Your top level call here is `mlrmbo_optimization`, which is a function from `nichenetr`. Have you tried to ask them? https://github.com/saeyslab/nichenetr/issues The error is deep in the nichenet code, which I have little knowledge about, in OmnipathR we only have a thin wrapper around it.

In general, I would check if the `igraph`, `mlrMBO`, `mlr`, `parallelMap` and `nichenetr` packages are all the latest versions. If you've run your code successfully before, I would check for recent updates, e.g. new `igraph` came out 2 months ago. Would be also interesting if you experience the error with any input or only for certain networks? I think in NicheNet errors are often related to particular network topologies, especially disconnected components.

Best,

Denes

**Comment by adesalegn** [comment]
Hi deeenes,

Thank you for the reply. However, is there any possibility to download the
following files  Results/Optimization_results.rds,
Results/weighted_networksNonSourceWeights.rds,
Results/ligand_target_matrixNoweights.rds,
Results/ligand_target_matrixWithweights.rds,
Results/weighted_networksWithSourceWeights.rds

Thank you!
Best,
AD

**Comment by deeenes** [comment]
Hi,

Is this about the case study in last years paper? I am transferring this issue to the relevant repository, where you can find the necessary information, or ask Alberto.

Best,

Denes

**Comment by alberto-valdeolivas** [comment]
Hello @adesalegn, 

Sorry, I missed this message. In case you are still interested in these files, could you send me your email? I can deposit them in some location and share them with you. Some of the files are too big for github. 

Best,
Alberto.

**Comment by adesalegn** [comment]
Sure, here it is. ***@***.***
Thanks!

**Comment by alberto-valdeolivas** [comment]
You can try to download them from here: 

https://filedropper.com/d/s/hIJnhBAuKjlFYOWGFFpLOtXkWxnXX6

Let me know if it works.

Alberto.

**Comment by alberto-valdeolivas** [comment]
Hello,

I generated a shareable link containing the files. Let me know if it works

https://1drv.ms/u/s!AsEej4TsWiVfgeAnQyVo40qn0Tcn8g?e=p94Ofb

Alberto
