### ISSUE TITLE
load_db() function

### ISSUE THREAD

**Issue by kir1to455** [saezlab/OmnipathR#40]
Hi Deeenes,

I was using your package for my study and I want to use the load_db() function in dbmanager.R, but I couldn't find it exists in package.
Did I miss something important?

Best wishes,
Kirito

**Comment by deeenes** [comment]
Hi Kirito,

The function `load_db` should be exported, unless you use a very old version of the package (before spring last year). However, better to use `get_db` instead. I created a little vignette about the database manager, I think this might help to clarify what it is and how does it work: https://saezlab.github.io/OmnipathR/articles/db_manager.html

Best,

Denes

**Comment by kir1to455** [comment]
Thanks for your help！

Best wishes
