### ISSUE TITLE
import_omnipath_enzsub() not returning 'n_references'

### ISSUE THREAD

**Issue by magdalenahuebner** [saezlab/OmnipathR#43]
Hi Denes,

Whenever I run the import_omnipath_enzsub() or import_omnipath_interactions() function, the 'n_references' column doesn't contain the number of references, but their Pubmed IDs (it's basically a copy of the 'references' column).
I'm using the 3.5.0 version, it used to work with the older version I was using before.

Thank you!

**Comment by deeenes** [comment]
Thanks a lot for finding this - as you see the fix was easy :)

**Comment by magdalenahuebner** [comment]
That was quick! Thank you :)
