### ISSUE TITLE
resources not accessible

### ISSUE THREAD

**Issue by AmelZulji** [saezlab/OmnipathR#45]
Hi folks, 

Following code:
```
signalink_pathways <-
  OmnipathR::import_omnipath_annotations(
    resources = 'SignaLink_pathway',
    entity_types = 'protein',
    wide = TRUE
  ) %>%
  select(genesymbol, pathway)
```

Produces following error:
`Error in open.connection(con, "rb") : HTTP error 500.`

Any idea how to solve it? 

Thank you and regards,
Amel

**Comment by deeenes** [comment]
Hi Amel,

It seems to be fine now, Friday I've done a couple of hours maintenance, exactly when you tried to use it.

Best,

Denes
