### ISSUE TITLE
https://omnipathdb.org/ - 500 Internal Server Error

### ISSUE THREAD

**Issue by georgia-katsoula** [saezlab/OmnipathR#46]
Hi, 

thank you for developing Omnipath, I have been trying to retrieve interaction data from the [https://omnipathdb.org](https://omnipathdb.org/) using the function `import_ligrecextra_interactions()`. 

However, I get the error: 
```Error in open.connection(structure(9L, class = c("curl", "connection"), conn_id = <pointer: 0xabd>), : HTTP error 500.```. 

I checked further if I can download the data from the link:
[https://omnipathdb.org/interactions?genesymbols=yes&datasets=ligrecextra&organisms=9606&fields=sources,references,curation_effort&license=academic](https://omnipathdb.org/interactions?genesymbols=yes&datasets=ligrecextra&organisms=9606&fields=sources,references,curation_effort&license=academic) but no link to [https://omnipathdb.org/](https://omnipathdb.org/)  is currently working for me and I get `500 Internal Server Error`.  

Thank you in advance for looking into it (@deeenes) :).

Best wishes,
Georgia

**Comment by georgia-katsoula** [comment]
Thank you, it works fine for me now.

Best,
Georgia

**Comment by deeenes** [comment]
Hi Georgia,

I think that day I've done a 1-2 hours maintenance, and you tried to use it exactly that time.

Best,

Denes
