### ISSUE TITLE
get Ramilowski2015 interaction dataset from omnipath

### ISSUE THREAD

**Issue by jinyuanchun** [saezlab/OmnipathR#50]
Hi thanks for a great package! i question is how to get  Ramilowski2015 interaction dataset from omnipath? 
thank you for your help!

**Comment by deeenes** [comment]
Hi,

There are three ways to get this resource:

1) From the OmniPath interactions database:

```
library(OmnipathR)

rami <- import_omnipath_interactions(resources = 'Ramilowski2015')
```

2) Use also the OmniPath intercell database for ligand and receptor annotations:

```
library(OmnipathR)

rami <- import_intercell_network(
    interactions_param = list(resources = 'Ramilowski2015'),
    transmitter_param = list(resources = 'Ramilowski2015', parent = 'ligand'),
    receiver_param = list(resources = 'Ramilowski2015', parent = 'receptor')
)
```

3) Downloading directly from the Ramilowski 2015 paper:

```
library(OmnipathR)

rami <- ramilowski_download()
```

The latest table will be exactly as it is in the paper, without any processing, which makes it slightly more difficult to work with.

Best,

Denes
