### ISSUE TITLE
error in 'map()' OmniPathR

### ISSUE THREAD

**Issue by EAbBcn** [saezlab/OmnipathR#61]
Hi OmniPathR team, can someone helps on this, please? I got this error running any interactions query functions in R, after properly installing OmniPathR package in R 4.2.2:

Error in `mutate()`:
i In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
i In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
x Problematic argument:
* outsep = outsep
Run `rlang::last_error()` to see where the error occurred.

**Comment by deeenes** [comment]
Hello, I believe this has been already fixed in 68e5aa0 (same as #56 and #57). If you install from the master branch it should work.

**Comment by EAbBcn** [comment]
Great, using master branch worked! Thanks deenes!
