### ISSUE TITLE
Building NicheNet PK with error

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/OmnipathR#63]
Hi @deeenes,

I was trying to run the `nichenet_main(tiny=True)` pipeline and I get the output save to "nichenet_results/networks.rds".

However, I also get the following error when it tries to optimize the network:

`Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 160 slave jobs, displaying at most 10 of them:`

`object 'ncitations' not found`

Any idea how can we resolve this?

Thanks!
Daniel

**Comment by deeenes** [comment]
Hi @dbdimitrov, This error should be addressed by running [`OmnipathR::nichenet_workarounds`](https://r.omnipathdb.org/reference/nichenet_workarounds.html) or attaching the `nichenetr` package. Then you can expect other errors from NicheNet, I'll forward you a recent email about those.

Best,
Denes
