### ISSUE TITLE
object ‘homologene_download’ is not exported by 'namespace:OmnipathR'

### ISSUE THREAD

**Issue by skylarsiwu0113** [saezlab/OmnipathR#65]
Hi,

I'm trying to install "LIANA" package, it seems like the installment was successful, but when I load the liana package, it shows `object ‘homologene_download’ is not exported by 'namespace:OmnipathR'`. Since LIANA uses OmnipathR as the dependent resource, I wonder could you please let me know how to fix it so that I can run LIANA? Thank you!

**Comment by deeenes** [comment]
Hi @skylarsiwu0113, Sorry, I missed your message until now. Most likely you have an old version of OmnipathR installed. I recommend to update it to the current master branch, using `remotes::install_github`. As you see, in the current version `homologene_download` [is exported](https://github.com/saezlab/OmnipathR/blob/1cbeae5b7a8fe81347795b6a06bb75c49c59b2a1/NAMESPACE#L65).
