### ISSUE TITLE
OmnipathR import functions mutate error

### ISSUE THREAD

**Issue by D-Harouni** [saezlab/OmnipathR#66]
For all import functions, e.i: OmnipathR::import_omnipath_interactions()

omnipath returns the following error:
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep

**Comment by deeenes** [comment]
Hello, You should update the package, for more details, please see the pinned issue #57
