### ISSUE TITLE
Error in get_dorothea

### ISSUE THREAD

**Issue by DylanPostmus** [saezlab/OmnipathR#68]
Hi,

I am having some trouble with the get_dorothea function of the decoupleR package (version 2.4.0).
When I run 

```r
net <- decoupleR::get_dorothea(organism='human', levels=c('A', 'B', 'C'))
```

I get the following error:

Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
Run `rlang::last_trace()` to see where the error occurred.

Could this be an issue with a tidyverse package? 

Thanks in advance.

**Comment by deeenes** [comment]
The error in your previous comment is the same as in #57, and has been fixed some weeks ago. The next error that you experience is not a problem with this package, but an issue with the installation or loading on your system, and most likely can be addressed by simply restarting R.
