### ISSUE TITLE
error in dplyr mutate function within get dorothea during omnipath

### ISSUE THREAD

**Issue by narmadabc** [saezlab/OmnipathR#70]
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep

**Comment by narmadabc** [comment]
├─OmnipathR:::strip_resource_labels(., inplace = FALSE, method = n_distinct)
 23. │ └─OmnipathR:::split_unique_join(...)
 24. │   └─OmnipathR:::split_apply(x = x, method = method, sep = sep, outsep = outsep)
 25. │     └─x %>% strsplit(sep) %>% map(method, ...) %>% unlist()

**Comment by narmadabc** [comment]
can you please advice how to fix this error?

**Comment by deeenes** [comment]
This error has been fixed in 68e5aa0 (see also the pinned issue #57)
