### ISSUE TITLE
error in homology_translate 

### ISSUE THREAD

**Issue by gabora** [saezlab/OmnipathR#71]
Hi Denes, 

I'm trying to translate mouse to human genes using the following command:  

```{r}
 OmnipathR::homology_translate(d = c("Agtr2","Akr1c18",  "Btla"),target = "human",source = "mouse",ensembl_orthology_types = "one2one")
```

This leads to the error 
```{r}
Error in `sym()`:
! Can't convert a character `NA` to a symbol.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 
```

The line that throws the error is this: 

[target2_id_type <- sym(id_types[3])](https://github.com/saezlab/OmnipathR/blob/48f64ecd3f0be356d9b6e217405e5a3cdee8dcdb/R/homology.R#LL151C10-L151C40)

the issue seems to be that `id_types` is length of 2

**Comment by deeenes** [comment]
Hi Attila, That function is not supposed to work yet, I shouldn't have exported it. Currently [this function](https://r.omnipathdb.org/reference/orthology_translate_column.html) should work for homology translation.
