### ISSUE TITLE
Wrong version packages

### ISSUE THREAD

**Issue by Icekirakira** [saezlab/OmnipathR#72]
Hi, 

Thanks for collating such a great database. 

I am trying to install version 3.16 (for R 4.2), but the installation package seems to be of a lower version. Thus, I am unable to use this version for get_collectri. Could you kindly look into this issue?

Here is the code and the feedback I get.

> BiocManager::install('OmnipathR', version = '3.16', force =T)
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.0 (2022-04-22)
Installing package(s) 'OmnipathR'
trying URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/OmnipathR_3.5.25.tar.gz'

**Comment by deeenes** [comment]
Hi, 3.16 is an expired version of Bioconductor. We backported CollecTRI to the current stable version 3.17. Some features that we recently introduced for a better processing of CollecTRI are not yet in either BioC devel or 3.17, it takes time until we get successful builds there. I recommend to install it directly from github:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```
