### ISSUE TITLE
Omnipath database

### ISSUE THREAD

**Issue by chrkuo** [saezlab/OmnipathR#73]
Hi I am trying to use omnipath as a reference database on NICHES. 

I have a few question. 

1. How do i look at a list of the database of receptor ligand? 

2. is there a bug in the database because when i loaded it to run there are errors that keep popping up.

NICHES_output <- RunNICHES(object = EWS4512,
                           LR.database = "omnipath",
                           species = "human",
                           assay = "alra",
                           position.x = 'x',
                           position.y = 'y',
                           k = 4, 
                           cell_types = "seurat_clusters",
                           min.cells.per.ident = 0,
                           min.cells.per.gene = NULL,
                           meta.data.to.map = names(EWS4512@meta.data), 
                           CellToCell = F,CellToSystem = F,SystemToCell = F, 
                           CellToCellSpatial = F,CellToNeighborhood = F,NeighborhoodToCell = T) 
                           
                           Error: 
**Set cell types as Identity of object internally

 Subsetting to populations with greater than 0 cells

 1437 distinct cells from 7 celltypes to be analyzed
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
Run `rlang::last_trace()` to see where the error occurred.**

**Comment by deeenes** [comment]
Hello,

The issue that you're experiencing has been fixed long time ago (#57), you can update the package directly from git:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```

There are two kinds of ligand-receptor networks that you can retrieve from OmniPath: one is in silico constructed from many resources, it has high coverage, but lot of false positives, though you can do some quality filtering on it; and there are the literature curated ligand-receptor interactions. Please take a look at the documentation of the following functions, and if any of your questions remain unanswered, feel free to ask again: [1](https://r.omnipathdb.org/reference/curated_ligand_receptor_interactions.html), [2](https://r.omnipathdb.org/reference/import_intercell_network.html), [3](https://r.omnipathdb.org/reference/filter_intercell_network.html).
