### ISSUE TITLE
Unable to install LIANA because of omnipathr dependency

### ISSUE THREAD

**Issue by joan-yanqiong** [saezlab/OmnipathR#78]
Hello, I'm trying to install LIANA but I keep getting this error: 

I'm using R 4.2.1 and tried the following commands to install: 
`
# Installing OmniPathR separately
pak::pkg_install("OmnipathR")
pacman::p_load("OmnipathR")
pacman::p_load("saezlab/OmnipathR")

pacman::p_load("saezlab/liana")

`
I also tried devtools. 

`Error: package or namespace load failed for ‘OmnipathR’:
 .onLoad failed in loadNamespace() for 'OmnipathR', details:
  call: yaml.load(readLines(con, warn = readLines.warn), error.label = error.label, 
  error: (~/.config/OmnipathR/omnipathr.yml) Parser error: did not find expected <document start> at line 2, column 1
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/tmp/RtmpAjqUpN/pkg-lib426e5fe821e0/OmnipathR’
Type .Last.error to see the more details.`

I hope you can help, thanks in advance!

**Comment by deeenes** [comment]
Hi,

Sorry for the late answer! It looks like an issue with the line endings or encoding of the file `~/.config/OmnipathR/omnipathr.yml`. What do you see if you look into this file:

```
# in bash:
less ~/.config/OmnipathR/omnipathr.yml
```

Or check it by `wc` and `file`:

```
# in bash:
wc ~/.config/OmnipathR/omnipathr.yml
file ~/.config/OmnipathR/omnipathr.yml
```

Do you experience the same error when you directly call `yaml.load` on the file?

```
library(yaml)
yaml.load(readLines(file('~/.config/OmnipathR/omnipathr.yml')))
```

What does the `readLines` return?

```
readLines(file('~/.config/OmnipathR/omnipathr.yml'))
```

Is it different if you specify an encoding?

```
readLines(file('~/.config/OmnipathR/omnipathr.yml', encoding = 'UTF-8'))
```

Which operating system are you using?
