### ISSUE TITLE
CellPhoneDB Version

### ISSUE THREAD

**Issue by SimonDMurray** [saezlab/OmnipathR#85]
Hi,

Sorry if this information is available somewhere but I cannot find it. I would like to know what version of cellphoneDB you have inside the OmniPathR package.

I see in your FAQ it says:
```
How often do you update OmniPath?
We add new resources every couple of months. 
We also update all the resources at least once a year. 
Most of the original resources don't update their contents so often, 
and some of them do it at a higher frequency. 
Before every update we archive the data. A log of updates is also available here.
```

However, in this log of updates I see the latest update to CellPhoneDB was in 2021.

I also noticed that you have forked the TeichLab CellPhoneDB [repo](https://github.com/saezlab/cellphonedb_omnipath).

I am not sure if this is where you are pulling CellPhoneDB from but if you are then I would suggest looking at the Vento lab [repo](https://github.com/ventolab/CellphoneDB) as that is where the latest versions of CellPhoneDB go. 

The latest version according to the [CellPhoneDB website](https://www.cellphonedb.org) is 4.1.0, if this is not the version used in OmniPathR is it possible to update it to this version?

Thanks for all your help!
Simon

**Comment by deeenes** [comment]
Hi, Good question, and it reminded me that others too have asked the same, n[ow I answered it under the other issue](https://github.com/saezlab/pypath/issues/200#issuecomment-1727979045)

**Comment by SimonDMurray** [comment]
Hi,

Thanks so much!

Simon
