### ISSUE TITLE
import_all_interactions only shows transcriptional

### ISSUE THREAD

**Issue by mschubert** [saezlab/OmnipathR#91]
Hi @deeenes,

I've run into the following issue with `OmnipathR`:

```r
library(OmnipathR)
tx = import_transcriptional_interactions()    # 128218 rows
tl = import_post_translational_interactions() # 134282 rows
all = import_all_interactions()               # 128218 rows
table(all$type, useNA="always")
# transcriptional            <NA>
#          128218               0
```

It seems that by default, all interactions returns only transcriptional interactions. This was not the case when I ran the same analysis a couple of months ago.

At the very least this is a bit confusing, but is this the intended output at all?

**Comment by deeenes** [comment]
Hello Michael, Great that you found this issue, it's absolutely not right for this function to return only transcriptional. It was a server side error, and I've just fixed it. I've also done some minor tweaks in this package, but I think it should work with the old version too. Maybe you have to remove the cache file, and maybe that's only possible by looking into the log:

```
library(OmnipathR)
omnipath_set_console_loglevel('trace')
all <- import_all_interactions()
# ... see the cache file, delete it
omnipath_cache_clean_db()
all <- import_all_interactions()
```

**Comment by deeenes** [comment]
Btw, also in this function `dorothea_levels` is A and B by default, you can override it:

```
import_all_interactions(dorothea_levels = c('A', 'B', 'C', 'D'))
```
