### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by ojikj2019** [saezlab/OmnipathR#92]
Hello,

When I tried to run the script, get_interaction_resources(), following installation and load the OmnipathR package, I got the error message below;

> get_interaction_resources()
Error in file(con, "r") : 
  cannot open the connection to 'https://omnipathdb.org/resources'

Could you please help me solve this problem?

Many thanks!

Jinhong

**Comment by deeenes** [comment]
Hello,

Thanks for reporting this! The server process was dead and unable to restart due to an interrupted system update yesterday. I've just fixed it now and should be working already.

Best,

Denes

**Comment by ojikj2019** [comment]
Hello Denes,

Thank you so much for your support! Yes, I've just successfully done running the script.

Best,

Jinhong
