### ISSUE TITLE
cannot open the connection to 'https://omnipathdb.org/resources'

### ISSUE THREAD

**Issue by jtorrejon81** [saezlab/OmnipathR#93]
Hello,

Many thanks for the nice tool. I was using OmnipathR without any problem during all year but Today when I tried to load the prior knowledge interactions, composed by kinase-target relationships

**uniprot_kinases <- OmnipathR::import_omnipath_annotations(resources = "UniProt_keyword") %>%
  dplyr::filter(value == "Kinase" & !grepl("COMPLEX", uniprot)) %>%
  distinct() %>%
  pull(genesymbol) %>%
  unique()**

I got the following error related to connection problem to Omnipath server

**Error in file(con, "r") : 
  cannot open the connection to 'https://omnipathdb.org/resources'**

I am wondering if it is due to a server issue since there was a very similar issue (https://github.com/saezlab/OmnipathR/issues/92) two days ago

Many thanks for your help
Best,
Jacob

**Comment by deeenes** [comment]
Hello Jacob,

Thanks for reporting this issue. The reason this time was insufficient resources (especially memory) in the server. As a quick fix I manually restarted the service now, though this error might pop up again, until hopefully in 1-2 months from now we address the real performance issue.

Best,

Denes

**Comment by jtorrejon81** [comment]
Many thanks Denes for your quick reply and help

Best,
Jacob
