### ISSUE TITLE
Omnipath failing to install in GitHub actions.

### ISSUE THREAD

**Issue by enblacar** [saezlab/OmnipathR#95]
Hi,

Thank you for this awesome package!

I would like to draw the attention to the following error log I get when using GitHub actions to check my package. This happens regardless of platform and R version:

```
 ✔ Packaged OmnipathR 3.11.1 (5.3s)
  ℹ Building OmnipathR 3.11.1
  ✖ Failed to build OmnipathR 3.11.1
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package OmnipathR.
  ---
  Backtrace:
  1. pak::lockfile_install(".github/pkg.lock")
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
   1. base::withCallingHandlers(cli_message = function(msg) { …
   2. get("lockfile_install_internal", asNamespace("pak"))(...)
   3. plan$install()
   4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
   5. base::withCallingHandlers({ …
   6. pkgdepends:::handle_events(state, events)
   7. pkgdepends:::handle_event(state, i)
   8. pkgdepends:::stop_task(state, worker)
   9. pkgdepends:::stop_task_build(state, worker)
  10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
  11. | base::signalCondition(cond)
  12. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

Are there any updates on when this could be fixed? 

Thanks a lot in advance.
Enrique

**Comment by Nic-Nic** [comment]
Hi @enblacar,

Reverted some of the last commits as they seemed to have caused some trouble with the installation to several users.
The current version in the master branch is now installing fine for me in a fresh installation of R, hope it also works for you.
We will work on fixing the last additions that caused the trouble before merging them back to master.

Best

**Comment by joan-yanqiong** [comment]
Hi, I also have the same problem, when using GitHub actions when using the dev version. Is there any solution for this?

**Comment by deeenes** [comment]
Hi @joan-yanqiong, Please open a new issue with a the output of `R CMD INSTALL` or any specific error message that you encounter.

```
git clone --depth 1 OmnipathR
cd OmnipathR
R CMD INSTALL .
```

In this issue there is no information even about the original problem, which has been supposedly resolved in February, and 4 months later we are already way ahead, let's investigate your current problem independently.
