### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ndrubins** [saezlab/OmnipathR#96]
Hi,

I first tried installing `OmnipathR` (using `devtools::install_github('saezlab/OmnipathR',force=T)`) and got the error:
`object ‘separate_wider_delim’ is not exported by 'namespace:tidyr'`

I then updated my `tidyr` installation and managed to complete the installation of `OmnipathR` but when trying to load it I still get the same error.

Any idea?

Thanks

**Comment by deeenes** [comment]
Hello, 

`separate_wider_delim` is part of the current `tidyr` API: https://tidyr.tidyverse.org/reference/separate_wider_delim.html

Might it be you load the package from a different library than the one you've updated in? I would check and it by `.libPaths()` and make sure `tidyr` is the latest version everywhere.

What concerns us, I'll set a minimum version for this dependency.

Best,

Denes

**Comment by deeenes** [comment]
Might it be your second error is a different one? Actually the tip of master branch wasn't possible to install over the past couple of weeks (see #95), and we've just reverted some commits that caused the issue, it should be fine again.

**Comment by ndrubins** [comment]
Hi,

Thanks a lot for the quick responses. What worked for me was to update all `R` packages that `OmnipathR` listed that are not up to the latest release.

Thanks
